### ISSUE TITLE
Audio Issues

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/enigma-dev#441]
There are several audio bugs that need worked out.
- [x] sound_volume() is also not working, reported in #408
- [x] sound_add() is also not working, reported in #412
- [x] audio_stop_all() reported in #548 
- [x] channel id's are not serialized #430; fixed in #586
- [x] distance falloff/attenuation is not implemented. implemented in #572
