### ISSUE TITLE
Debug mode code that needs to be added

### ISSUE THREAD

**Issue by polygoned** [enigma-dev/enigma-dev#566]
This topic is to list all the debug code that should be added to the ENIGMA source. There is a lot missing at the moment which causes segfaults that are difficult to debug.
- [ ] If you call d3d_primitive_end(); before calling d3d_primitive_begin(); then it segfaults. Calling multiple d3d_primitive_end() or d3d_primitive_being() will probably also mess up but not tested
- [ ] Missing container macros, eg. get_texture and other shits
- [x] Debug macro for non-existant objects #411, basically same issue as "treat unitialized variables as 0" probably needs done by Josh
- [ ] Debugging for Data Structures need added as discovered in #592 
- [x] #801 Instance and room creation code need better syntax checking.
- [ ] Fix crash by implementing debug error message #811 when setting a room background visible but not actually setting a background

**Comment by RobertBColton** [comment]
The primitive thing is no longer an issue since all of that code is generic. If one now calls end without calling begin, it should just hypothetically be cancelled from the model. It was in #1366 that we ensured a Model's current primitive always exists, even if it's empty.

**Comment by fundies** [comment]
@RobertBColton are any of these still issues? All the linked issues seem closed

**Comment by RobertBColton** [comment]
Only some of those were resolved, the others were closed specifically because they are listed here.

**Comment by fundies** [comment]
you say primitive isnt an issue above so can check that one and any others that are resolved

**Comment by RobertBColton** [comment]
We could still warn about it, since GMS does, as it is pretty senseless to call end without begin. The last one there with regard to a visible background where the background doesn't exist is a sticky one. If I recall Josh debated checking for it in the engine, because it could also be detected by the IDE. I guess we haven't really decided yet what should be compile time vs runtime checked. That could maybe even be checked in both cases. I do know that debugging needs to be added for data structures, there's absolutely no bounds checking done. I could go accomplish that one.
